import type { NutrientKey, NutrientTargets } from "@/types/nutrition";

// USDA FDC nutrient ID → our key
export const NUTRIENT_ID_MAP: Record<number, NutrientKey> = {
  1008: "calories",
  1003: "protein",
  1004: "fat",
  1005: "carbs",
  1079: "fiber",
  2000: "sugar",
  1106: "vitA",
  1165: "vitB1",
  1166: "vitB2",
  1167: "vitB3",
  1170: "vitB5",
  1175: "vitB6",
  1178: "vitB12",
  1162: "vitC",
  1110: "vitD",
  1109: "vitE",
  1185: "vitK",
  1177: "folate",
  1087: "calcium",
  1089: "iron",
  1090: "magnesium",
  1092: "potassium",
  1093: "sodium",
  1095: "zinc",
  1103: "selenium",
  1091: "phosphorus",
  1098: "copper",
  1101: "manganese",
};

export const NUTRIENT_UNITS: Record<NutrientKey, string> = {
  calories: "kcal",
  protein: "g",
  carbs: "g",
  fat: "g",
  fiber: "g",
  sugar: "g",
  vitA: "mcg",
  vitB1: "mg",
  vitB2: "mg",
  vitB3: "mg",
  vitB5: "mg",
  vitB6: "mg",
  vitB12: "mcg",
  vitC: "mg",
  vitD: "mcg",
  vitE: "mg",
  vitK: "mcg",
  folate: "mcg",
  calcium: "mg",
  iron: "mg",
  magnesium: "mg",
  potassium: "mg",
  sodium: "mg",
  zinc: "mg",
  selenium: "mcg",
  phosphorus: "mg",
  copper: "mg",
  manganese: "mg",
};

export const NUTRIENT_LABELS: Record<NutrientKey, string> = {
  calories: "Calories",
  protein: "Protein",
  carbs: "Carbohydrates",
  fat: "Fat",
  fiber: "Fiber",
  sugar: "Sugar",
  vitA: "Vitamin A",
  vitB1: "B1 · Thiamin",
  vitB2: "B2 · Riboflavin",
  vitB3: "B3 · Niacin",
  vitB5: "B5 · Pantothenic",
  vitB6: "Vitamin B6",
  vitB12: "Vitamin B12",
  vitC: "Vitamin C",
  vitD: "Vitamin D",
  vitE: "Vitamin E",
  vitK: "Vitamin K",
  folate: "Folate",
  calcium: "Calcium",
  iron: "Iron",
  magnesium: "Magnesium",
  potassium: "Potassium",
  sodium: "Sodium",
  zinc: "Zinc",
  selenium: "Selenium",
  phosphorus: "Phosphorus",
  copper: "Copper",
  manganese: "Manganese",
};

export const DEFAULT_TARGETS: NutrientTargets = {
  calories: 2000,
  protein: 150,
  carbs: 200,
  fat: 65,
  fiber: 25,
  sugar: 50,
  vitA: 900,
  vitB1: 1.2,
  vitB2: 1.3,
  vitB3: 16,
  vitB5: 5,
  vitB6: 1.7,
  vitB12: 2.4,
  vitC: 90,
  vitD: 20,
  vitE: 15,
  vitK: 120,
  folate: 400,
  calcium: 1000,
  iron: 8,
  magnesium: 420,
  potassium: 3500,
  sodium: 2300,
  zinc: 11,
  selenium: 55,
  phosphorus: 700,
  copper: 0.9,
  manganese: 2.3,
};

export const VITAMIN_KEYS: NutrientKey[] = [
  "vitA","vitB1","vitB2","vitB3","vitB5","vitB6",
  "vitB12","vitC","vitD","vitE","vitK","folate",
];

export const MINERAL_KEYS: NutrientKey[] = [
  "calcium","iron","magnesium","potassium","sodium",
  "zinc","selenium","phosphorus","copper","manganese",
];

export const MACRO_KEYS: NutrientKey[] = ["protein","carbs","fat","fiber","sugar"];

export const MEAL_TYPES = ["Breakfast","Lunch","Dinner","Snacks"] as const;
